### ISSUE TITLE
Sources of the used certificates

### ISSUE THREAD

**Issue by c33s** [xenetis/letsencrypt-expiration#2]
it would be awesome if you would provide the sources of the certificates used in this repo or even better change the script to download them from the official sources rather than using the certs from this repo.

official links (https://letsencrypt.org/certificates/):
- https://letsencrypt.org/certs/lets-encrypt-r3.pem
- https://letsencrypt.org/certs/isrgrootx1.pem

**Comment by Herz3h** [comment]
This was a bad idea, since letsencrypt.org is signed with CA authority. For instance here are the lgos:

```
Connecting to letsencrypt.org (letsencrypt.org)|3.67.234.155|:443... connected.
GnuTLS: Resource temporarily unavailable, try again.
GnuTLS: Resource temporarily unavailable, try again.
GnuTLS: Resource temporarily unavailable, try again.
ERROR: The certificate of 'letsencrypt.org' is not trusted.
ERROR: The certificate of 'letsencrypt.org' has expired.
--2021-12-17 09:38:36--  https://letsencrypt.org/certs/isrgrootx1.pem
```

**Comment by c33s** [comment]
valid point. maybe the best thing would be to 

- add an option so you can choose if to use the letsencrypt certs or the provided certs from this repo. 
- add an option to run wget with `--no-check-certificate`
- keep the orinal sources of the certs in the readme

its about trusting certificates from a 3rd party repo or trusting wget to run with  `--no-check-certificate` while downloading from letsencrypt.org

**Comment by xenetis** [comment]
Scripts updated, thanks guys
