### ISSUE TITLE
Rename .pem to .crt

### ISSUE THREAD

**Issue by p0wertiger** [xenetis/letsencrypt-expiration#5]
According to manual of update-ca-certificates:

> Furthermore all certificates with a .crt extension found below /usr/local/share/ca-certificates are also included as implicitly trusted.

Thus, you need to rename all downloaded .pem files to .crt. 

Example for `rename` from a perl extension package `rename`:
`rename "s/pem$/crt/" /usr/local/share/ca-certificates/*.pem`

Same for package `util-linux`:
`rename.ul .pem .crt /tmp/abc/*.pem`

**Comment by xenetis** [comment]
fixed here https://github.com/xenetis/letsencrypt-expiration/commit/3f983d6dcff2743eada2b908ad850196df59f7a0
